# Generated by Django 6.0.3 on 2026-04-08 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_api', '0007_alter_chargingstation_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Phường/Xã')),
                ('district', models.CharField(default='Ba Đình', max_length=100, verbose_name='Quận/Huyện')),
                ('city', models.CharField(default='Hà Nội', max_length=100, verbose_name='Thành phố')),
            ],
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='charging_api.ward'),
        ),
    ]
