# Generated by Django 6.0.3 on 2026-04-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_api', '0008_ward_chargingstation_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lịch hẹn'),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='vehicle_density',
            field=models.CharField(default='Thấp', max_length=50, verbose_name='Mật độ xe'),
        ),
    ]
